/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.sql.SQLException;

public class App {

    public static void main(String[] args) throws SQLException {
        
    
        
    }
}
